services:
  app:
    build: .
    ports:
      - "9000"
    depends_on:
      - db
  db:
    image: "postgis/postgis:16-3.4"
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: APass
    ports:
      - "9001:5432"
